### ISSUE TITLE
As a logged-in user I can see when the order is ready, I can see details of all my orders including how much time it will take for the order to be fulfilled since the ordering time.

### ISSUE THREAD

**Issue by mata0050** [mata0050/midterm#13]

**Comment by RReiso** [comment]
There should be an update in `users/:id/orders` view next to each order

**Comment by RReiso** [comment]
This is when user goes to `users/:id/orders` and sees all their orders' details and status. The app can flash a message as well when the order is ready with a text "Your order is ready! You will receive an SMS confirmation shortly!"
